import { useEffect, useMemo, useState } from "react";
import AuthScreen from "../auth/AuthScreen";
import { getCurrentProfile, signOut } from "../auth/authService";
import { addPayment, createEvent, listEvents } from "../modules/events/eventService";
import { eventStatusLabel } from "../modules/events/demoEvents";
import { ars } from "../shared/money";
import { isSupabaseConfigured, supabase } from "../supabase/client";

export default function App() {
  const [session, setSession] = useState(undefined); const [profile, setProfile] = useState(null); const [events, setEvents] = useState([]); const [search, setSearch] = useState(""); const [showEventForm, setShowEventForm] = useState(false); const [paymentEvent, setPaymentEvent] = useState(null); const [message, setMessage] = useState("");
  const refreshEvents = async () => setEvents(await listEvents());
  useEffect(() => { if (!supabase) { setSession(null); return; } supabase.auth.getSession().then(({ data }) => setSession(data.session)); const { data: listener } = supabase.auth.onAuthStateChange((_event, current) => setSession(current)); return () => listener.subscription.unsubscribe(); }, []);
  useEffect(() => { if (!session) return; Promise.all([getCurrentProfile(), listEvents()]).then(([currentProfile, currentEvents]) => { setProfile(currentProfile); setEvents(currentEvents); }).catch((error) => setMessage(error.message)); }, [session]);
  const filteredEvents = useMemo(() => events.filter((event) => `${event.client} ${event.packageName}`.toLowerCase().includes(search.toLowerCase())), [events, search]);
  const totals = useMemo(() => events.reduce((result, event) => ({ sold: result.sold + event.total, collected: result.collected + event.paid }), { sold: 0, collected: 0 }), [events]);
  async function createInquiry(event) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await createEvent({ clientName: data.get("client"), packageName: data.get("package"), total: Number(data.get("total")), date: data.get("date"), time: data.get("time"), userId: session.user.id }); await refreshEvents(); setShowEventForm(false); setMessage("Consulta creada correctamente."); } catch (error) { setMessage(error.message); } }
  async function registerPayment(event) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await addPayment({ eventId: paymentEvent.id, amount: Number(data.get("amount")), note: data.get("note"), userId: session.user.id }); await refreshEvents(); setPaymentEvent(null); setMessage("Pago registrado. El estado del evento se actualizó según la seña acumulada."); } catch (error) { setMessage(error.message); } }
  async function claimOwner() { const { error } = await supabase.rpc("claim_first_owner"); if (error) { setMessage(error.message); return; } setProfile(await getCurrentProfile()); setMessage("Tu cuenta ahora es la dueña de GrowUp."); }
  if (!isSupabaseConfigured) return <main className="auth-page"><section className="auth-card"><h1>Falta conectar Supabase</h1><p>Vercel debe terminar de aplicar las variables del proyecto.</p></section></main>;
  if (session === undefined) return <main className="auth-page">Cargando GrowUp…</main>;
  if (!session) return <AuthScreen />;
  return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">G</span><div><strong>GrowUp</strong><small>Eventos & experiencias</small></div></div><div className="account"><span className="avatar">{profile?.full_name?.slice(0, 2).toUpperCase() ?? "GU"}</span><span>{profile?.full_name ?? session.user.email} · {profile?.role ?? "cargando"}</span><button className="sign-out" onClick={signOut}>Salir</button></div></header>{message && <div className="setup-notice">{message}</div>}<div className="workspace"><main><section className="heading"><div><p>Panel de eventos</p><h1>Todo bajo control.</h1><span>Ventas, señas y eventos en un solo lugar.</span></div><button className="primary" onClick={() => setShowEventForm(true)}>+ Nuevo evento</button></section>{profile?.role === "seller" && <button className="link-button" onClick={claimOwner}>Activar esta primera cuenta como dueña</button>}<section className="metrics"><Metric label="Vendido" value={ars(totals.sold)} detail="Eventos registrados" tone="purple"/><Metric label="Cobrado" value={ars(totals.collected)} detail="Señas y pagos cargados" tone="pink"/><Metric label="Pendiente" value={ars(totals.sold - totals.collected)} detail="Saldos por cobrar" tone="amber"/></section><section className="content-grid"><article className="agenda"><div className="section-head"><div><h2>Agenda</h2><span>{events.length} eventos y consultas</span></div><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar evento" /></div><div className="event-list">{filteredEvents.map((item) => <div className="event" key={item.id}><time>{item.time}</time><i/><div className="event-main"><b>{item.client}</b><span>{item.packageName}</span></div><div className="event-meta"><b>{ars(item.total)}</b><em className={item.status}>{eventStatusLabel[item.status]}</em><button className="link-button" onClick={() => setPaymentEvent(item)}>{item.paid ? "Registrar pago" : "Registrar seña"}</button></div></div>)}{filteredEvents.length === 0 && <p className="empty">Todavía no hay eventos. Creá la primera consulta para empezar.</p>}</div></article><div className="side"><article className="result"><span>Resultado estimado</span><strong>{ars(totals.collected)}</strong><small>Se descontarán los costos cuando se carguen.</small></article><article className="review"><h2>Seña obligatoria</h2><p><i/><span><strong>10% para confirmar</strong><br/>El sistema confirma el evento al llegar a ese importe.</span></p></article></div></section></main></div>{showEventForm && <EventForm onClose={() => setShowEventForm(false)} onSubmit={createInquiry}/>} {paymentEvent && <PaymentForm event={paymentEvent} onClose={() => setPaymentEvent(null)} onSubmit={registerPayment}/>}</div>;
}

function EventForm({ onClose, onSubmit }) { return <div className="modal-backdrop"><form className="modal" onSubmit={onSubmit}><button className="close" type="button" onClick={onClose}>×</button><h2>Nueva consulta</h2><label>Cliente<input name="client" required /></label><label>Paquete o servicio<input name="package" required /></label><div className="form-row"><label>Fecha<input name="date" type="date" required /></label><label>Horario<input name="time" type="time" required /></label></div><label>Total acordado<input name="total" type="number" min="0" required /></label><div className="actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary" type="submit">Crear consulta</button></div></form></div>; }
function PaymentForm({ event, onClose, onSubmit }) { const requiredDeposit = Math.ceil(event.total * 0.1); const remainingForDeposit = Math.max(requiredDeposit - event.paid, 0); return <div className="modal-backdrop"><form className="modal" onSubmit={onSubmit}><button className="close" type="button" onClick={onClose}>×</button><h2>Registrar pago</h2><p>{event.client} · total {ars(event.total)}</p><p>Seña mínima: {ars(requiredDeposit)}. Falta para confirmar: {ars(remainingForDeposit)}.</p><label>Importe recibido<input name="amount" type="number" min="1" required defaultValue={remainingForDeposit || ""}/></label><label>Nota opcional<input name="note" placeholder="Ej. transferencia" /></label><div className="actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary" type="submit">Registrar pago</button></div></form></div>; }
function Metric({ label, value, detail, tone }) { return <article className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }
